import { MarkdownRenderChild, Notice } from "obsidian";
import type { SynologyApi } from "./synology-api";
import type { SynologyLinkSettings } from "./settings";
import { EditorView } from "@codemirror/view";

type GetSettings = () => SynologyLinkSettings;

/** Pattern that identifies File Station URLs generated by this plugin. */
const FILE_STATION_MARKER = "launchApp=SYNO.SDS.App.FileStation3.Instance";

/**
 * Extract a NAS file path from a File Station URL's launchParam.
 * Returns null if the URL is not a File Station link.
 */
function extractFileStationPath(href: string): string | null {
  if (!href.includes(FILE_STATION_MARKER)) return null;
  const match = href.match(/launchParam=([^&]+)/);
  if (!match) return null;
  const param = decodeURIComponent(match[1]); // "openfile=/Alexandria/..."
  return param.replace(/^openfile=/, "") || null;
}

/**
 * Open the authenticated download URL for a NAS file path.
 */
async function openDownload(api: SynologyApi, filePath: string): Promise<void> {
  try {
    const url = await api.getDownloadUrl(filePath);
    window.open(url, "_blank");
  } catch (e) {
    new Notice(
      e instanceof Error
        ? e.message
        : "Failed to download file. Check your connection settings."
    );
  }
}

/**
 * Reading View: intercepts clicks on File Station links to trigger
 * authenticated downloads (when downloadOnClick is enabled).
 */
export class DownloadOnClickChild extends MarkdownRenderChild {
  private api: SynologyApi;
  private getSettings: GetSettings;

  constructor(
    containerEl: HTMLElement,
    api: SynologyApi,
    getSettings: GetSettings
  ) {
    super(containerEl);
    this.api = api;
    this.getSettings = getSettings;
  }

  onload(): void {
    const link = this.containerEl as HTMLAnchorElement;
    const href = link.getAttribute("href");
    if (!href) return;

    const filePath = extractFileStationPath(href);
    if (!filePath) return;

    this.registerDomEvent(link, "click", (evt: MouseEvent) => {
      if (!this.getSettings().downloadOnClick) return; // let browser handle normally
      evt.preventDefault();
      evt.stopPropagation();
      openDownload(this.api, filePath);
    });
  }
}

/**
 * Live Preview: intercepts clicks on File Station links when
 * downloadOnClick is enabled.
 */
export function buildLivePreviewExtension(
  api: SynologyApi,
  getSettings: GetSettings
) {
  return EditorView.domEventHandlers({
    click: (evt: MouseEvent, view: EditorView) => {
      if (!getSettings().downloadOnClick) return false;

      const target = evt.target as HTMLElement;

      const linkEl =
        target.closest(".cm-underline") ||
        target.closest(".external-link");
      if (!linkEl) return false;

      const pos = view.posAtDOM(target);
      const line = view.state.doc.lineAt(pos);

      const regex = /\[[^\]]*\]\(([^)]+)\)/g;
      let match;
      while ((match = regex.exec(line.text)) !== null) {
        const matchStart = line.from + match.index;
        const matchEnd = matchStart + match[0].length;

        if (pos >= matchStart && pos <= matchEnd) {
          const fsPath = extractFileStationPath(match[1]);
          if (fsPath) {
            evt.preventDefault();
            evt.stopPropagation();
            openDownload(api, fsPath);
            return true;
          }
        }
      }

      return false;
    },
  });
}
